### ISSUE TITLE
地图缓存设置无效，切换路由之后依然实例化了一个 Map 对象

### ISSUE THREAD

**Issue by PeachScript** [anypossiblew/ui-map-baidu#1]
你好，非常感谢你写的地图组件，我在使用中遇到了一个问题：将 `uiMapCache` 设置为 `true`， 但切换路由之后发现还是重新实例化了一个 Map 对象，并且往这个新的 Map 对象中添加 `Marker` 也没有任何作用了，不知这是因为什么？

研究了一下源代码，好像没有发现 cache map 对象的语句，但找到了检测 cache 和读取 cache 的部分，请问这算是一个 bug 吗？

**Comment by anypossiblew** [comment]
非常感谢你能提出此bug，此缓存地图的功能在1.1.6版本中已添加，请查看demo。
