### ISSUE TITLE
ui-map-info-window里面的ng-click事件无法触发

### ISSUE THREAD

**Issue by gundamlbn** [anypossiblew/ui-map-baidu#2]
参照示例的写法
data-ng-click="console.log('click');setMarkerPosition(currentMarker, currentMarkerLat, currentMarkerLng)"
但是demo里面的此事件也无法执行。
求教ng-click的写法

**Comment by gundamlbn** [comment]
找到解决方案了

``` html
<div id="myInfoWindow" ui-map-info-window="myInfoWindow" ng-click="select($event, item.uid)">
                    <h4 class="text-primary" ng-bind="item.userId"></h4>
                    <img style="float:right;margin:4px;max-height:100px;max-width:100px">
                    <address>
                    姓名:<span ng-bind="item.name"></span><br>
                    </address>
                    <button id="selectSupplier" class="btn btn-primary">选择</button>
                </div>
```

``` javascript
        $scope.select = function(e, uid){
            console.log(e);
            // 点击选中
            if(e.target.tagName == 'BUTTON'){
                AlertService.confirm('确认', '确定选择此用户?', function(){

                });
            }
        };
```

**Comment by gundamlbn** [comment]
找到解决方案了
···
                <div id="myInfoWindow" ui-map-info-window="myInfoWindow" ng-click="select($event, item.uid)">
                    <h4 class="text-primary" ng-bind="item.userId"></h4>
                    <img style="float:right;margin:4px;max-height:100px;max-width:100px">
                    <address>
                    姓名:<span ng-bind="item.name"></span><br>
                    </address>
                    <button id="selectSupplier" class="btn btn-primary">选择</button>
                </div>
···
···
        $scope.select = function(e, uid){
            console.log(e);
            // 点击选中
            if(e.target.tagName == 'BUTTON'){
                AlertService.confirm('确认', '确定选择此用户?', function(){
                    
                });
            }
        };
···

**Comment by e-cloud** [comment]
@gundamlbn, 根本没有用好不好！

**Comment by e-cloud** [comment]
@anypossiblew, `uiMapInfoWindowConfig`指令里的这一段

```
              var _redraw = infoWindow.redraw;
              infoWindow.redraw = function open(a1, a2, a3, a4, a5, a6) {
                $compile(elm.contents())(scope);
                _redraw.call(infoWindow, a1, a2, a3, a4, a5, a6);
              };
```

根本没用，因为redraw根本没有被调用到，$compile没有运行，数据没有绑定！

**Comment by anypossiblew** [comment]
把infoWindow的方法改成show就可以了。

```
          var _show = infoWindow.show;
          infoWindow.show = function open(a1, a2, a3, a4, a5, a6) {
            $compile(elm.contents())(scope);
            _show.call(infoWindow, a1, a2, a3, a4, a5, a6);
          };
```
